version: 2
updates:
    -   package-ecosystem: "docker"
        directory: "/"
        schedule:
            interval: "weekly"
        labels:
            - "dependencies"
            - "docker"
        open-pull-requests-limit: 10
        pull-request-branch-name:
            separator: "-"
        rebase-strategy: "auto"
        target-branch: "master"

    -   package-ecosystem: "pip"
        directory: "/"
        schedule:
            interval: "daily"
        labels:
            - "dependencies"
        open-pull-requests-limit: 10
        pull-request-branch-name:
            separator: "-"
        rebase-strategy: "auto"
        target-branch: "master"
