apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: gold-digger-cron-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gold-digger-cron-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 85
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageUtilization: 85
        type: Utilization