apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: gold-digger-cron-deployment
    labels:
        app: gold-digger-cron
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gold-digger-cron
    template:
        metadata:
            labels:
                app: gold-digger-cron
        spec:
            containers:
                -   name: golddigger-cron-master
                    image: eu.gcr.io/roihunter-master/roihunter/golddigger:$BUILD_NUMBER
                    imagePullPolicy: Always
                    readinessProbe:
                        exec:
                            command:
                                - echo
                                - "OK!"
                        initialDelaySeconds: 5
                        periodSeconds: 30
                    command: ["python"]
                    args: ["-m", "gold_digger", "cron"]
                    env:
                        -   name: GOLD_DIGGER_DATABASE_HOST
                            value: "35.205.178.65"
                        -   name: GOLD_DIGGER_DATABASE_PORT
                            value: "5432"
                        -   name: GOLD_DIGGER_PROFILE
                            value: "master"
                    envFrom:
                        -   secretRef:
                                name: gold-digger-master
                    ports:
                        -   containerPort: 8080
                    resources:
                        limits:
                            memory: "100Mi"
                            cpu: "300m"
                        requests:
                            memory: "100Mi"
                            cpu: "100m"
