apiVersion: apps/v1
kind: Deployment
metadata:
    name: gold-digger-cron-deployment
    labels:
        app: gold-digger-cron
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gold-digger-cron
    template:
        metadata:
            labels:
                app: gold-digger-cron
        spec:
            containers:
                -   name: golddigger-cron-master
                    image: eu.gcr.io/roihunter-master/roihunter/golddigger:$BUILD_NUMBER
                    imagePullPolicy: Always
                    readinessProbe:
                        exec:
                            command:
                                - echo
                                - "OK!"
                        initialDelaySeconds: 5
                        periodSeconds: 30
                    command: [ "python" ]
                    args: [ "-m", "gold_digger", "cron" ]
                    env:
                        -   name: GOLD_DIGGER_APP_VERSION
                            value: "$APP_VERSION"
                        -   name: GOLD_DIGGER_DATABASE_HOST
                            value: "10.76.176.10"
                        -   name: GOLD_DIGGER_DATABASE_PORT
                            value: "5432"
                        -   name: GOLD_DIGGER_PROFILE
                            value: "master"
                    envFrom:
                        -   secretRef:
                                name: gold-digger-master
                    ports:
                        -   containerPort: 8080
                    resources:
                        limits:
                            memory: "0.5"
                            cpu: "0.25"
                        requests:
                            memory: "0.25"
                            cpu: "0.1"
