apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: gold-digger-hpa
spec:
    maxReplicas: 10
    minReplicas: 2
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: gold-digger-deployment
    metrics:
        -   type: Resource
            resource:
                name: cpu
                target:
                    averageUtilization: 85
                    type: Utilization
        -   type: Resource
            resource:
                name: memory
                target:
                    averageUtilization: 85
                    type: Utilization
